### ISSUE TITLE
Fails to load, import error

### ISSUE THREAD

**Issue by aurel-g** [JustinMatters/comfyUI-JMNodes#4]
```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/comfyUI-JMNodes/__init__.py", line 3, in <module>
    from .nodes.JMSwitchablePrompt import *
ModuleNotFoundError: No module named 'comfyUI-JMNodes.nodes.JMSwitchablePrompt'

Cannot import /mnt/comfyui/app/custom_nodes/comfyUI-JMNodes module for custom nodes: No module named 'comfyUI-JMNodes.nodes.JMSwitchablePrompt'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/comfyUI-JMNodes

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by aurel-g** [comment]
Thank you for merging.
